version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sistema_vendas # Banco de dados unificado
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d # Scripts de inicialização
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  cliente-service:
    build: ./cliente-service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://myuser:myuserpassword@mysql/sistema_vendas
    ports:
      - "5001:5000" # Mapeia a porta para permitir acesso pelo navegador

  produto-service:
    build: ./produto-service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://myuser:myuserpassword@mysql/sistema_vendas
    ports:
      - "5000:5000"

  venda-service:
    build: ./venda-service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://myuser:myuserpassword@mysql/sistema_vendas
    ports:
      - "8080:8080"

  frontend-service:
    build: ./frontend-service
    container_name: frontend
    restart: always
    ports:
      - "80:80" # Porta para acessar no navegador
    depends_on:
      - cliente-service
      - produto-service
      - venda-service

volumes:
  mysql_data:
